-- ============================================================
-- Buying - AS-IS DDL (PostgreSQL) generated from DocType JSON
-- Mirrors the ERPNext physical layout: business-key PK, no FK constraints.
-- ============================================================

-- Customer Number At Supplier (child)
CREATE TABLE "tabCustomer Number At Supplier" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  company varchar(140),
  customer_number varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_customer_number_at_supplier_parent ON "tabCustomer Number At Supplier" (parent);

-- Purchase Order (transaction)
CREATE TABLE "tabPurchase Order" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  title varchar(140),
  naming_series varchar(140),
  supplier varchar(140),
  supplier_name varchar(140),
  company varchar(140),
  transaction_date date,
  schedule_date date,
  order_confirmation_no varchar(140),
  order_confirmation_date date,
  amended_from varchar(140),
  customer varchar(140),
  customer_name varchar(140),
  customer_contact_person varchar(140),
  customer_contact_display text,
  customer_contact_mobile text,
  customer_contact_email text,
  supplier_address varchar(140),
  contact_person varchar(140),
  address_display text,
  contact_display text,
  contact_mobile text,
  contact_email text,
  shipping_address varchar(140),
  shipping_address_display text,
  currency varchar(140),
  conversion_rate numeric(21,9),
  buying_price_list varchar(140),
  price_list_currency varchar(140),
  plc_conversion_rate numeric(21,9),
  ignore_pricing_rule smallint,
  set_warehouse varchar(140),
  is_subcontracted smallint,
  supplier_warehouse varchar(140),
  scan_barcode varchar(140),
  total_qty numeric(21,9),
  base_total numeric(21,9),
  base_net_total numeric(21,9),
  total numeric(21,9),
  net_total numeric(21,9),
  total_net_weight numeric(21,9),
  taxes_and_charges varchar(140),
  shipping_rule varchar(140),
  other_charges_calculation text,
  base_taxes_and_charges_added numeric(21,9),
  base_taxes_and_charges_deducted numeric(21,9),
  base_total_taxes_and_charges numeric(21,9),
  taxes_and_charges_added numeric(21,9),
  taxes_and_charges_deducted numeric(21,9),
  total_taxes_and_charges numeric(21,9),
  apply_discount_on varchar(140),
  base_discount_amount numeric(21,9),
  additional_discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  base_grand_total numeric(21,9),
  base_rounding_adjustment numeric(21,9),
  base_in_words varchar(140),
  base_rounded_total numeric(21,9),
  grand_total numeric(21,9),
  rounding_adjustment numeric(21,9),
  rounded_total numeric(21,9),
  disable_rounded_total smallint,
  in_words varchar(140),
  advance_paid numeric(21,9),
  payment_terms_template varchar(140),
  tc_name varchar(140),
  terms text,
  status varchar(140),
  ref_sq varchar(140),
  party_account_currency varchar(140),
  inter_company_order_reference varchar(140),
  per_received numeric(21,9),
  per_billed numeric(21,9),
  letter_head varchar(140),
  select_print_heading varchar(140),
  group_same_items smallint,
  language varchar(140),
  from_date date,
  to_date date,
  auto_repeat varchar(140),
  tax_category varchar(140),
  set_reserve_warehouse varchar(140),
  billing_address varchar(140),
  billing_address_display text,
  is_internal_supplier smallint,
  represents_company varchar(140),
  cost_center varchar(140),
  project varchar(140),
  set_from_warehouse varchar(140),
  incoterm varchar(140),
  named_place varchar(140),
  advance_payment_status varchar(140),
  has_unit_price_items smallint,
  dispatch_address varchar(140),
  dispatch_address_display text,
  supplier_group varchar(140),
  mps varchar(140),
  transaction_time time(6)
);
CREATE INDEX ix_purchase_order_supplier ON "tabPurchase Order" (supplier);
CREATE INDEX ix_purchase_order_transaction_date ON "tabPurchase Order" (transaction_date);
CREATE INDEX ix_purchase_order_status ON "tabPurchase Order" (status);

-- Purchase Order Item (child)
CREATE TABLE "tabPurchase Order Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  supplier_part_no varchar(140),
  item_name varchar(140),
  schedule_date date,
  expected_delivery_date date,
  description text,
  image text,
  qty numeric(21,9),
  stock_uom varchar(140),
  uom varchar(140),
  conversion_factor numeric(21,9),
  price_list_rate numeric(21,9),
  discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  last_purchase_rate numeric(21,9),
  base_price_list_rate numeric(21,9),
  rate numeric(21,9),
  amount numeric(21,9),
  base_rate numeric(21,9),
  base_amount numeric(21,9),
  pricing_rules text,
  is_free_item smallint,
  net_rate numeric(21,9),
  net_amount numeric(21,9),
  base_net_rate numeric(21,9),
  base_net_amount numeric(21,9),
  weight_per_unit numeric(21,9),
  total_weight numeric(21,9),
  weight_uom varchar(140),
  warehouse varchar(140),
  project varchar(140),
  material_request varchar(140),
  material_request_item varchar(140),
  sales_order varchar(140),
  sales_order_item varchar(140),
  supplier_quotation varchar(140),
  supplier_quotation_item varchar(140),
  delivered_by_supplier smallint,
  blanket_order varchar(140),
  blanket_order_rate numeric(21,9),
  item_group varchar(140),
  brand varchar(140),
  bom varchar(140),
  stock_qty numeric(21,9),
  received_qty numeric(21,9),
  returned_qty numeric(21,9),
  billed_amt numeric(21,9),
  item_tax_rate text,
  expense_account varchar(140),
  cost_center varchar(140),
  page_break smallint,
  item_tax_template varchar(140),
  manufacturer varchar(140),
  manufacturer_part_no varchar(140),
  against_blanket_order smallint,
  is_fixed_asset smallint,
  stock_uom_rate numeric(21,9),
  actual_qty numeric(21,9),
  company_total_stock numeric(21,9),
  margin_type varchar(140),
  margin_rate_or_amount numeric(21,9),
  rate_with_margin numeric(21,9),
  base_rate_with_margin numeric(21,9),
  production_plan varchar(140),
  production_plan_item varchar(140),
  production_plan_sub_assembly_item varchar(140),
  product_bundle varchar(140),
  sales_order_packed_item varchar(140),
  fg_item varchar(140),
  fg_item_qty numeric(21,9),
  from_warehouse varchar(140),
  wip_composite_asset varchar(140),
  job_card varchar(140),
  distributed_discount_amount numeric(21,9),
  subcontracted_qty numeric(21,9),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_purchase_order_item_expected_delivery_date ON "tabPurchase Order Item" (expected_delivery_date);
CREATE INDEX ix_purchase_order_item_material_request ON "tabPurchase Order Item" (material_request);
CREATE INDEX ix_purchase_order_item_material_request_item ON "tabPurchase Order Item" (material_request_item);
CREATE INDEX ix_purchase_order_item_sales_order ON "tabPurchase Order Item" (sales_order);
CREATE INDEX ix_purchase_order_item_sales_order_item ON "tabPurchase Order Item" (sales_order_item);
CREATE INDEX ix_purchase_order_item_parent ON "tabPurchase Order Item" (parent);

-- Purchase Receipt Item Supplied (child)
CREATE TABLE "tabPurchase Receipt Item Supplied" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  main_item_code varchar(140),
  rm_item_code varchar(140),
  description text,
  batch_no varchar(140),
  serial_no text,
  required_qty numeric(21,9),
  consumed_qty numeric(21,9),
  stock_uom varchar(140),
  rate numeric(21,9),
  amount numeric(21,9),
  conversion_factor numeric(21,9),
  current_stock numeric(21,9),
  reference_name varchar(140),
  bom_detail_no varchar(140),
  item_name varchar(140),
  purchase_order varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_purchase_receipt_item_supplied_parent ON "tabPurchase Receipt Item Supplied" (parent);

-- Request for Quotation (transaction)
CREATE TABLE "tabRequest for Quotation" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  company varchar(140),
  vendor varchar(140),
  transaction_date date,
  email_template varchar(140),
  message_for_supplier text,
  tc_name varchar(140),
  terms text,
  select_print_heading varchar(140),
  letter_head varchar(140),
  opportunity varchar(140),
  status varchar(140),
  amended_from varchar(140),
  schedule_date date,
  incoterm varchar(140),
  named_place varchar(140),
  send_attached_files smallint,
  send_document_print smallint,
  billing_address varchar(140),
  billing_address_display text,
  has_unit_price_items smallint,
  subject varchar(140),
  mfs_html text,
  use_html smallint,
  shipping_address varchar(140),
  shipping_address_display text,
  title varchar(140)
);
CREATE INDEX ix_request_for_quotation_company ON "tabRequest for Quotation" (company);
CREATE INDEX ix_request_for_quotation_transaction_date ON "tabRequest for Quotation" (transaction_date);
CREATE INDEX ix_request_for_quotation_status ON "tabRequest for Quotation" (status);

-- Request for Quotation Item (child)
CREATE TABLE "tabRequest for Quotation Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  supplier_part_no varchar(140),
  item_name varchar(140),
  description text,
  image text,
  qty numeric(21,9),
  schedule_date date,
  uom varchar(140),
  warehouse varchar(140),
  project_name varchar(140),
  material_request varchar(140),
  material_request_item varchar(140),
  brand varchar(140),
  item_group varchar(140),
  page_break smallint,
  stock_uom varchar(140),
  conversion_factor numeric(21,9),
  stock_qty numeric(21,9),
  cost_center varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_request_for_quotation_item_item_code ON "tabRequest for Quotation Item" (item_code);
CREATE INDEX ix_request_for_quotation_item_item_name ON "tabRequest for Quotation Item" (item_name);
CREATE INDEX ix_request_for_quotation_item_parent ON "tabRequest for Quotation Item" (parent);

-- Request for Quotation Supplier (child)
CREATE TABLE "tabRequest for Quotation Supplier" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  send_email smallint,
  email_sent smallint,
  supplier varchar(140),
  contact varchar(140),
  quote_status varchar(140),
  supplier_name varchar(140),
  email_id varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_request_for_quotation_supplier_parent ON "tabRequest for Quotation Supplier" (parent);

-- Supplier (master)
CREATE TABLE "tabSupplier" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  supplier_name varchar(140),
  country varchar(140),
  default_bank_account varchar(140),
  tax_id varchar(140),
  tax_category varchar(140),
  tax_withholding_category varchar(140),
  is_transporter smallint,
  is_internal_supplier smallint,
  represents_company varchar(140),
  image text,
  supplier_group varchar(140),
  supplier_type varchar(140),
  language varchar(140),
  disabled smallint,
  warn_rfqs smallint,
  warn_pos smallint,
  prevent_rfqs smallint,
  prevent_pos smallint,
  default_currency varchar(140),
  default_price_list varchar(140),
  payment_terms varchar(140),
  on_hold smallint,
  hold_type varchar(140),
  release_date date,
  website varchar(140),
  supplier_details text,
  is_frozen smallint,
  allow_purchase_invoice_creation_without_purchase_order smallint,
  allow_purchase_invoice_creation_without_purchase_receipt smallint,
  supplier_primary_contact varchar(140),
  mobile_no varchar(140),
  email_id varchar(140),
  primary_address text,
  supplier_primary_address varchar(140),
  restrict_to_companies smallint,
  tax_withholding_group varchar(140),
  gender varchar(140),
  alias varchar(140)
);

-- Supplier Quotation (transaction)
CREATE TABLE "tabSupplier Quotation" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  title varchar(140),
  naming_series varchar(140),
  supplier varchar(140),
  supplier_name varchar(140),
  transaction_date date,
  amended_from varchar(140),
  company varchar(140),
  supplier_address varchar(140),
  contact_person varchar(140),
  address_display text,
  contact_display text,
  contact_mobile text,
  contact_email varchar(140),
  currency varchar(140),
  conversion_rate numeric(21,9),
  buying_price_list varchar(140),
  price_list_currency varchar(140),
  plc_conversion_rate numeric(21,9),
  ignore_pricing_rule smallint,
  total_qty numeric(21,9),
  base_total numeric(21,9),
  base_net_total numeric(21,9),
  total numeric(21,9),
  net_total numeric(21,9),
  total_net_weight numeric(21,9),
  tax_category varchar(140),
  shipping_rule varchar(140),
  taxes_and_charges varchar(140),
  other_charges_calculation text,
  base_taxes_and_charges_added numeric(21,9),
  base_taxes_and_charges_deducted numeric(21,9),
  base_total_taxes_and_charges numeric(21,9),
  taxes_and_charges_added numeric(21,9),
  taxes_and_charges_deducted numeric(21,9),
  total_taxes_and_charges numeric(21,9),
  apply_discount_on varchar(140),
  base_discount_amount numeric(21,9),
  additional_discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  base_grand_total numeric(21,9),
  base_rounding_adjustment numeric(21,9),
  base_in_words varchar(140),
  base_rounded_total numeric(21,9),
  grand_total numeric(21,9),
  rounding_adjustment numeric(21,9),
  rounded_total numeric(21,9),
  in_words varchar(140),
  disable_rounded_total smallint,
  tc_name varchar(140),
  terms text,
  select_print_heading varchar(140),
  group_same_items smallint,
  letter_head varchar(140),
  language varchar(140),
  auto_repeat varchar(140),
  status varchar(140),
  is_subcontracted smallint,
  opportunity varchar(140),
  valid_till date,
  quotation_number varchar(140),
  incoterm varchar(140),
  named_place varchar(140),
  shipping_address varchar(140),
  shipping_address_display text,
  billing_address varchar(140),
  billing_address_display text,
  cost_center varchar(140),
  project varchar(140),
  has_unit_price_items smallint
);
CREATE INDEX ix_supplier_quotation_supplier ON "tabSupplier Quotation" (supplier);
CREATE INDEX ix_supplier_quotation_transaction_date ON "tabSupplier Quotation" (transaction_date);
CREATE INDEX ix_supplier_quotation_company ON "tabSupplier Quotation" (company);
CREATE INDEX ix_supplier_quotation_status ON "tabSupplier Quotation" (status);

-- Supplier Quotation Item (child)
CREATE TABLE "tabSupplier Quotation Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  supplier_part_no varchar(140),
  item_name varchar(140),
  lead_time_days integer,
  description text,
  image text,
  qty numeric(21,9),
  stock_uom varchar(140),
  price_list_rate numeric(21,9),
  discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  uom varchar(140),
  conversion_factor numeric(21,9),
  stock_qty numeric(21,9),
  base_price_list_rate numeric(21,9),
  rate numeric(21,9),
  amount numeric(21,9),
  base_rate numeric(21,9),
  base_amount numeric(21,9),
  pricing_rules text,
  net_rate numeric(21,9),
  net_amount numeric(21,9),
  base_net_rate numeric(21,9),
  base_net_amount numeric(21,9),
  weight_per_unit numeric(21,9),
  total_weight numeric(21,9),
  weight_uom varchar(140),
  warehouse varchar(140),
  project varchar(140),
  prevdoc_doctype varchar(140),
  material_request varchar(140),
  sales_order varchar(140),
  request_for_quotation varchar(140),
  item_tax_template varchar(140),
  material_request_item varchar(140),
  request_for_quotation_item varchar(140),
  brand varchar(140),
  item_group varchar(140),
  item_tax_rate text,
  page_break smallint,
  manufacturer varchar(140),
  manufacturer_part_no varchar(140),
  is_free_item smallint,
  expected_delivery_date date,
  cost_center varchar(140),
  distributed_discount_amount numeric(21,9),
  margin_type varchar(140),
  margin_rate_or_amount numeric(21,9),
  rate_with_margin numeric(21,9),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_supplier_quotation_item_item_code ON "tabSupplier Quotation Item" (item_code);
CREATE INDEX ix_supplier_quotation_item_item_name ON "tabSupplier Quotation Item" (item_name);
CREATE INDEX ix_supplier_quotation_item_material_request ON "tabSupplier Quotation Item" (material_request);
CREATE INDEX ix_supplier_quotation_item_sales_order ON "tabSupplier Quotation Item" (sales_order);
CREATE INDEX ix_supplier_quotation_item_material_request_item ON "tabSupplier Quotation Item" (material_request_item);
CREATE INDEX ix_supplier_quotation_item_parent ON "tabSupplier Quotation Item" (parent);

-- Supplier Scorecard (master)
CREATE TABLE "tabSupplier Scorecard" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  supplier varchar(140),
  supplier_score varchar(140),
  indicator_color varchar(140),
  status varchar(140),
  period varchar(140),
  weighting_function text,
  warn_rfqs smallint,
  warn_pos smallint,
  prevent_rfqs smallint,
  prevent_pos smallint,
  notify_supplier smallint,
  notify_employee smallint,
  employee varchar(140)
);

-- Supplier Scorecard Criteria (master)
CREATE TABLE "tabSupplier Scorecard Criteria" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  criteria_name varchar(140),
  max_score numeric(21,9),
  formula text,
  weight numeric(21,9)
);

-- Supplier Scorecard Period (transaction)
CREATE TABLE "tabSupplier Scorecard Period" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  supplier varchar(140),
  naming_series varchar(140),
  total_score numeric(21,9),
  start_date date,
  end_date date,
  scorecard varchar(140),
  amended_from varchar(140)
);

-- Supplier Scorecard Scoring Criteria (child)
CREATE TABLE "tabSupplier Scorecard Scoring Criteria" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  criteria_name varchar(140),
  score numeric(21,9),
  weight numeric(21,9),
  max_score numeric(21,9),
  formula text,
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_supplier_scorecard_scoring_criteria_parent ON "tabSupplier Scorecard Scoring Criteria" (parent);

-- Supplier Scorecard Scoring Standing (child)
CREATE TABLE "tabSupplier Scorecard Scoring Standing" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  standing_name varchar(140),
  standing_color varchar(140),
  min_grade numeric(21,9),
  max_grade numeric(21,9),
  warn_rfqs smallint,
  warn_pos smallint,
  prevent_rfqs smallint,
  prevent_pos smallint,
  notify_supplier smallint,
  notify_employee smallint,
  employee_link varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_supplier_scorecard_scoring_standing_parent ON "tabSupplier Scorecard Scoring Standing" (parent);

-- Supplier Scorecard Scoring Variable (child)
CREATE TABLE "tabSupplier Scorecard Scoring Variable" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  variable_label varchar(140),
  description text,
  value numeric(21,9),
  param_name varchar(140),
  path varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_supplier_scorecard_scoring_variable_parent ON "tabSupplier Scorecard Scoring Variable" (parent);

-- Supplier Scorecard Standing (master)
CREATE TABLE "tabSupplier Scorecard Standing" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  standing_name varchar(140),
  standing_color varchar(140),
  min_grade numeric(21,9),
  max_grade numeric(21,9),
  warn_rfqs smallint,
  warn_pos smallint,
  prevent_rfqs smallint,
  prevent_pos smallint,
  notify_supplier smallint,
  notify_employee smallint,
  employee_link varchar(140)
);

-- Supplier Scorecard Variable (master)
CREATE TABLE "tabSupplier Scorecard Variable" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  variable_label varchar(140),
  is_custom smallint,
  param_name varchar(140),
  path varchar(140),
  description text
);
