-- ============================================================
-- Selling - AS-IS DDL (PostgreSQL) generated from DocType JSON
-- Mirrors the ERPNext physical layout: business-key PK, no FK constraints.
-- ============================================================

-- Customer (master)
CREATE TABLE "tabCustomer" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  customer_name varchar(140),
  gender varchar(140),
  customer_type varchar(140),
  default_bank_account varchar(140),
  lead_name varchar(140),
  image text,
  account_manager varchar(140),
  customer_group varchar(140),
  territory varchar(140),
  tax_id varchar(140),
  tax_category varchar(140),
  disabled smallint,
  is_internal_customer smallint,
  represents_company varchar(140),
  default_currency varchar(140),
  default_price_list varchar(140),
  language varchar(140),
  website varchar(140),
  customer_primary_contact varchar(140),
  mobile_no varchar(140),
  email_id varchar(140),
  customer_primary_address varchar(140),
  primary_address text,
  payment_terms varchar(140),
  customer_details text,
  market_segment varchar(140),
  industry varchar(140),
  is_frozen smallint,
  loyalty_program varchar(140),
  loyalty_program_tier varchar(140),
  default_sales_partner varchar(140),
  default_commission_rate numeric(21,9),
  customer_pos_id varchar(140),
  so_required smallint,
  dn_required smallint,
  tax_withholding_category varchar(140),
  opportunity_name varchar(140),
  restrict_to_companies smallint,
  prospect_name varchar(140),
  first_name varchar(140),
  last_name varchar(140),
  tax_withholding_group varchar(140),
  alias varchar(140)
);
CREATE INDEX ix_customer_customer_name ON "tabCustomer" (customer_name);
CREATE INDEX ix_customer_customer_group ON "tabCustomer" (customer_group);

-- Customer Credit Limit (child)
CREATE TABLE "tabCustomer Credit Limit" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  credit_limit numeric(21,9),
  overdue_billing_threshold numeric(21,9),
  company varchar(140),
  bypass_credit_limit_check smallint,
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_customer_credit_limit_parent ON "tabCustomer Credit Limit" (parent);

-- Delivery Schedule Item (master)
CREATE TABLE "tabDelivery Schedule Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  qty numeric(21,9),
  conversion_factor numeric(21,9),
  stock_qty numeric(21,9),
  delivery_date date,
  sales_order varchar(140),
  sales_order_item varchar(140),
  warehouse varchar(140),
  uom varchar(140),
  stock_uom varchar(140)
);
CREATE INDEX ix_delivery_schedule_item_sales_order ON "tabDelivery Schedule Item" (sales_order);
CREATE INDEX ix_delivery_schedule_item_sales_order_item ON "tabDelivery Schedule Item" (sales_order_item);

-- Industry Type (master)
CREATE TABLE "tabIndustry Type" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  industry varchar(140)
);

-- Installation Note (transaction)
CREATE TABLE "tabInstallation Note" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  customer varchar(140),
  customer_address varchar(140),
  contact_person varchar(140),
  customer_name varchar(140),
  address_display text,
  contact_display text,
  contact_mobile text,
  contact_email varchar(140),
  territory varchar(140),
  customer_group varchar(140),
  inst_date date,
  inst_time time(6),
  status varchar(140),
  company varchar(140),
  amended_from varchar(140),
  remarks text,
  project varchar(140)
);
CREATE INDEX ix_installation_note_customer ON "tabInstallation Note" (customer);
CREATE INDEX ix_installation_note_territory ON "tabInstallation Note" (territory);
CREATE INDEX ix_installation_note_inst_date ON "tabInstallation Note" (inst_date);

-- Installation Note Item (child)
CREATE TABLE "tabInstallation Note Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  serial_no text,
  qty numeric(21,9),
  description text,
  prevdoc_detail_docname varchar(140),
  prevdoc_docname varchar(140),
  prevdoc_doctype varchar(140),
  serial_and_batch_bundle varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_installation_note_item_prevdoc_docname ON "tabInstallation Note Item" (prevdoc_docname);
CREATE INDEX ix_installation_note_item_prevdoc_doctype ON "tabInstallation Note Item" (prevdoc_doctype);
CREATE INDEX ix_installation_note_item_parent ON "tabInstallation Note Item" (parent);

-- Party Specific Item (master)
CREATE TABLE "tabParty Specific Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  party_type varchar(140),
  party varchar(140),
  restrict_based_on varchar(140),
  based_on_value varchar(140)
);

-- Product Bundle (transaction)
CREATE TABLE "tabProduct Bundle" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  new_item_code varchar(140),
  description varchar(140),
  is_active smallint,
  disabled smallint,
  amended_from varchar(140)
);

-- Product Bundle Item (child)
CREATE TABLE "tabProduct Bundle Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  qty numeric(21,9),
  description text,
  rate numeric(21,9),
  uom varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_product_bundle_item_parent ON "tabProduct Bundle Item" (parent);

-- Proforma Invoice (transaction)
CREATE TABLE "tabProforma Invoice" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  sales_order varchar(140),
  customer varchar(140),
  customer_name varchar(140),
  proforma_date date,
  company varchar(140),
  currency varchar(140),
  based_on varchar(140),
  hide_item_qty smallint,
  total_qty numeric(21,9),
  grand_total numeric(21,9),
  print_format varchar(140),
  letter_head varchar(140),
  proforma_pdf text,
  status varchar(140),
  sent_on timestamp,
  emailed_to text,
  amended_from varchar(140)
);

-- Proforma Invoice Item (child)
CREATE TABLE "tabProforma Invoice Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  item_name varchar(140),
  qty numeric(21,9),
  uom varchar(140),
  rate numeric(21,9),
  amount numeric(21,9),
  so_detail varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_proforma_invoice_item_parent ON "tabProforma Invoice Item" (parent);

-- Quotation (transaction)
CREATE TABLE "tabQuotation" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  quotation_to varchar(140),
  party_name varchar(140),
  customer_name varchar(140),
  amended_from varchar(140),
  company varchar(140),
  transaction_date date,
  valid_till date,
  order_type varchar(140),
  customer_address varchar(140),
  address_display text,
  contact_person varchar(140),
  contact_display text,
  contact_mobile text,
  contact_email varchar(140),
  shipping_address_name varchar(140),
  shipping_address text,
  customer_group varchar(140),
  territory varchar(140),
  currency varchar(140),
  conversion_rate numeric(21,9),
  selling_price_list varchar(140),
  price_list_currency varchar(140),
  plc_conversion_rate numeric(21,9),
  ignore_pricing_rule smallint,
  total_qty numeric(21,9),
  base_total numeric(21,9),
  base_net_total numeric(21,9),
  total numeric(21,9),
  net_total numeric(21,9),
  total_net_weight numeric(21,9),
  tax_category varchar(140),
  shipping_rule varchar(140),
  taxes_and_charges varchar(140),
  other_charges_calculation text,
  base_total_taxes_and_charges numeric(21,9),
  total_taxes_and_charges numeric(21,9),
  coupon_code varchar(140),
  referral_sales_partner varchar(140),
  apply_discount_on varchar(140),
  base_discount_amount numeric(21,9),
  additional_discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  base_grand_total numeric(21,9),
  base_rounding_adjustment numeric(21,9),
  base_in_words varchar(140),
  base_rounded_total numeric(21,9),
  grand_total numeric(21,9),
  rounding_adjustment numeric(21,9),
  rounded_total numeric(21,9),
  in_words varchar(140),
  payment_terms_template varchar(140),
  tc_name varchar(140),
  terms text,
  letter_head varchar(140),
  group_same_items smallint,
  select_print_heading varchar(140),
  language varchar(140),
  auto_repeat varchar(140),
  order_lost_reason text,
  status varchar(140),
  enq_det text,
  supplier_quotation varchar(140),
  opportunity varchar(140),
  company_address varchar(140),
  company_address_display text,
  scan_barcode varchar(140),
  incoterm varchar(140),
  named_place varchar(140),
  utm_campaign varchar(140),
  utm_source varchar(140),
  utm_medium varchar(140),
  utm_content varchar(140),
  disable_rounded_total smallint,
  company_contact_person varchar(140),
  has_unit_price_items smallint,
  title varchar(140)
);
CREATE INDEX ix_quotation_party_name ON "tabQuotation" (party_name);
CREATE INDEX ix_quotation_transaction_date ON "tabQuotation" (transaction_date);

-- Quotation Item (child)
CREATE TABLE "tabQuotation Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  is_product_bundle smallint,
  product_bundle varchar(140),
  customer_item_code varchar(140),
  item_name varchar(140),
  description text,
  image text,
  qty numeric(21,9),
  stock_uom varchar(140),
  uom varchar(140),
  conversion_factor numeric(21,9),
  stock_qty numeric(21,9),
  price_list_rate numeric(21,9),
  base_price_list_rate numeric(21,9),
  margin_type varchar(140),
  margin_rate_or_amount numeric(21,9),
  rate_with_margin numeric(21,9),
  discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  base_rate_with_margin numeric(21,9),
  rate numeric(21,9),
  net_rate numeric(21,9),
  amount numeric(21,9),
  net_amount numeric(21,9),
  base_rate numeric(21,9),
  base_net_rate numeric(21,9),
  base_amount numeric(21,9),
  base_net_amount numeric(21,9),
  pricing_rules text,
  is_free_item smallint,
  weight_per_unit numeric(21,9),
  total_weight numeric(21,9),
  weight_uom varchar(140),
  warehouse varchar(140),
  projected_qty numeric(21,9),
  actual_qty numeric(21,9),
  prevdoc_doctype varchar(140),
  prevdoc_docname varchar(140),
  item_tax_rate text,
  item_tax_template varchar(140),
  page_break smallint,
  item_group varchar(140),
  brand varchar(140),
  additional_notes text,
  blanket_order varchar(140),
  blanket_order_rate numeric(21,9),
  against_blanket_order smallint,
  valuation_rate numeric(21,9),
  gross_profit numeric(21,9),
  stock_uom_rate numeric(21,9),
  is_alternative smallint,
  has_alternative_item smallint,
  distributed_discount_amount numeric(21,9),
  company_total_stock numeric(21,9),
  ordered_qty numeric(21,9),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_quotation_item_item_code ON "tabQuotation Item" (item_code);
CREATE INDEX ix_quotation_item_parent ON "tabQuotation Item" (parent);

-- Sales Order (transaction)
CREATE TABLE "tabSales Order" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  naming_series varchar(140),
  customer varchar(140),
  customer_name varchar(140),
  order_type varchar(140),
  amended_from varchar(140),
  company varchar(140),
  transaction_date date,
  delivery_date date,
  po_no varchar(140),
  po_date date,
  tax_id varchar(140),
  customer_address varchar(140),
  address_display text,
  contact_person varchar(140),
  contact_display text,
  contact_mobile text,
  contact_email varchar(140),
  company_address_display text,
  company_address varchar(140),
  shipping_address_name varchar(140),
  shipping_address text,
  customer_group varchar(140),
  territory varchar(140),
  currency varchar(140),
  conversion_rate numeric(21,9),
  selling_price_list varchar(140),
  price_list_currency varchar(140),
  plc_conversion_rate numeric(21,9),
  ignore_pricing_rule smallint,
  set_warehouse varchar(140),
  scan_barcode varchar(140),
  total_qty numeric(21,9),
  base_total numeric(21,9),
  base_net_total numeric(21,9),
  total numeric(21,9),
  net_total numeric(21,9),
  total_net_weight numeric(21,9),
  tax_category varchar(140),
  shipping_rule varchar(140),
  taxes_and_charges varchar(140),
  other_charges_calculation text,
  base_total_taxes_and_charges numeric(21,9),
  total_taxes_and_charges numeric(21,9),
  loyalty_points integer,
  loyalty_amount numeric(21,9),
  coupon_code varchar(140),
  apply_discount_on varchar(140),
  base_discount_amount numeric(21,9),
  additional_discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  base_grand_total numeric(21,9),
  base_rounding_adjustment numeric(21,9),
  base_rounded_total numeric(21,9),
  base_in_words varchar(140),
  grand_total numeric(21,9),
  rounding_adjustment numeric(21,9),
  rounded_total numeric(21,9),
  in_words varchar(140),
  advance_paid numeric(21,9),
  payment_terms_template varchar(140),
  tc_name varchar(140),
  terms text,
  inter_company_order_reference varchar(140),
  project varchar(140),
  party_account_currency varchar(140),
  language varchar(140),
  letter_head varchar(140),
  select_print_heading varchar(140),
  group_same_items smallint,
  status varchar(140),
  delivery_status varchar(140),
  per_delivered numeric(21,9),
  per_billed numeric(21,9),
  billing_status varchar(140),
  sales_partner varchar(140),
  commission_rate numeric(21,9),
  total_commission numeric(21,9),
  from_date date,
  to_date date,
  auto_repeat varchar(140),
  contact_phone varchar(140),
  skip_delivery_note smallint,
  is_internal_customer smallint,
  represents_company varchar(140),
  disable_rounded_total smallint,
  dispatch_address_name varchar(140),
  dispatch_address text,
  amount_eligible_for_commission numeric(21,9),
  per_picked numeric(21,9),
  cost_center varchar(140),
  incoterm varchar(140),
  named_place varchar(140),
  reserve_stock smallint,
  advance_payment_status varchar(140),
  utm_medium varchar(140),
  utm_content varchar(140),
  utm_source varchar(140),
  utm_campaign varchar(140),
  company_contact_person varchar(140),
  has_unit_price_items smallint,
  is_subcontracted smallint,
  transaction_time time(6),
  ignore_default_payment_terms_template smallint,
  title varchar(140)
);
CREATE INDEX ix_sales_order_customer ON "tabSales Order" (customer);
CREATE INDEX ix_sales_order_transaction_date ON "tabSales Order" (transaction_date);
CREATE INDEX ix_sales_order_inter_company_order_reference ON "tabSales Order" (inter_company_order_reference);
CREATE INDEX ix_sales_order_project ON "tabSales Order" (project);
CREATE INDEX ix_sales_order_status ON "tabSales Order" (status);

-- Sales Order Item (child)
CREATE TABLE "tabSales Order Item" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  item_code varchar(140),
  is_product_bundle smallint,
  product_bundle varchar(140),
  customer_item_code varchar(140),
  ensure_delivery_based_on_produced_serial_no smallint,
  item_name varchar(140),
  description text,
  delivery_date date,
  image text,
  qty numeric(21,9),
  stock_uom varchar(140),
  uom varchar(140),
  conversion_factor numeric(21,9),
  stock_qty numeric(21,9),
  price_list_rate numeric(21,9),
  base_price_list_rate numeric(21,9),
  margin_type varchar(140),
  margin_rate_or_amount numeric(21,9),
  rate_with_margin numeric(21,9),
  discount_percentage numeric(21,9),
  discount_amount numeric(21,9),
  base_rate_with_margin numeric(21,9),
  rate numeric(21,9),
  amount numeric(21,9),
  base_rate numeric(21,9),
  base_amount numeric(21,9),
  pricing_rules text,
  is_free_item smallint,
  net_rate numeric(21,9),
  net_amount numeric(21,9),
  base_net_rate numeric(21,9),
  base_net_amount numeric(21,9),
  delivered_by_supplier smallint,
  supplier varchar(140),
  weight_per_unit numeric(21,9),
  total_weight numeric(21,9),
  weight_uom varchar(140),
  warehouse varchar(140),
  target_warehouse varchar(140),
  prevdoc_docname varchar(140),
  brand varchar(140),
  item_group varchar(140),
  billed_amt numeric(21,9),
  valuation_rate numeric(21,9),
  gross_profit numeric(21,9),
  blanket_order varchar(140),
  blanket_order_rate numeric(21,9),
  projected_qty numeric(21,9),
  actual_qty numeric(21,9),
  ordered_qty numeric(21,9),
  delivered_qty numeric(21,9),
  work_order_qty numeric(21,9),
  returned_qty numeric(21,9),
  item_tax_template varchar(140),
  page_break smallint,
  planned_qty numeric(21,9),
  produced_qty numeric(21,9),
  item_tax_rate text,
  transaction_date date,
  additional_notes text,
  against_blanket_order smallint,
  bom_no varchar(140),
  stock_uom_rate numeric(21,9),
  grant_commission smallint,
  picked_qty numeric(21,9),
  purchase_order varchar(140),
  purchase_order_item varchar(140),
  quotation_item varchar(140),
  material_request varchar(140),
  material_request_item varchar(140),
  reserve_stock smallint,
  stock_reserved_qty numeric(21,9),
  production_plan_qty numeric(21,9),
  is_stock_item smallint,
  distributed_discount_amount numeric(21,9),
  company_total_stock numeric(21,9),
  cost_center varchar(140),
  project varchar(140),
  subcontracted_qty numeric(21,9),
  fg_item varchar(140),
  fg_item_qty numeric(21,9),
  requested_qty numeric(21,9),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_sales_order_item_prevdoc_docname ON "tabSales Order Item" (prevdoc_docname);
CREATE INDEX ix_sales_order_item_purchase_order ON "tabSales Order Item" (purchase_order);
CREATE INDEX ix_sales_order_item_project ON "tabSales Order Item" (project);
CREATE INDEX ix_sales_order_item_parent ON "tabSales Order Item" (parent);

-- Sales Partner Type (master)
CREATE TABLE "tabSales Partner Type" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  sales_partner_type varchar(140)
);

-- Sales Team (child)
CREATE TABLE "tabSales Team" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  sales_person varchar(140),
  contact_no varchar(140),
  allocated_percentage numeric(21,9),
  allocated_amount numeric(21,9),
  commission_rate numeric(21,9),
  incentives numeric(21,9),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_sales_team_sales_person ON "tabSales Team" (sales_person);
CREATE INDEX ix_sales_team_parent ON "tabSales Team" (parent);

-- Supplier Number At Customer (child)
CREATE TABLE "tabSupplier Number At Customer" (
  name varchar(140) NOT NULL PRIMARY KEY,
  creation timestamp,
  modified timestamp,
  modified_by varchar(140),
  owner varchar(140),
  docstatus smallint NOT NULL DEFAULT 0,
  idx integer NOT NULL DEFAULT 0,
  company varchar(140),
  supplier_number varchar(140),
  parent varchar(140),
  parentfield varchar(140),
  parenttype varchar(140)
);
CREATE INDEX ix_supplier_number_at_customer_parent ON "tabSupplier Number At Customer" (parent);
