#!/usr/bin/env python3
"""Regenerate the coverage table inside docs/COVERAGE.md in place.

Replaces everything between the BEGIN/END COVERAGE TABLE markers with fresh output from
tools/coverage_audit.py --markdown, so the committed table can never drift from reality.

Usage:
    python3 tools/update_coverage_doc.py            # rewrite docs/COVERAGE.md
    python3 tools/update_coverage_doc.py --check    # exit 1 if the table is stale (for CI)
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from contextlib import redirect_stdout

from coverage_audit import audit, print_markdown

DOC = "docs/COVERAGE.md"
BEGIN = "<!-- BEGIN COVERAGE TABLE (generated by tools/coverage_audit.py --markdown) -->"
END = "<!-- END COVERAGE TABLE -->"


def render_table() -> str:
    buf = io.StringIO()
    with redirect_stdout(buf):
        print_markdown(audit())
    return buf.getvalue().rstrip("\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if stale instead of rewriting")
    args = ap.parse_args()

    with open(DOC, encoding="utf-8") as fh:
        content = fh.read()

    if BEGIN not in content or END not in content:
        sys.exit(f"markers not found in {DOC}")

    table = render_table()
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        f"{BEGIN}\n{table}\n{END}",
        content,
        flags=re.DOTALL,
    )

    if args.check:
        if new != content:
            sys.exit(f"{DOC} coverage table is stale — run: python3 tools/update_coverage_doc.py")
        print(f"{DOC} coverage table is up to date")
        return

    if new == content:
        print(f"{DOC} already up to date")
        return

    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write(new)
    print(f"updated {DOC}")


if __name__ == "__main__":
    main()
